#!/usr/bin/env bash

# Copyright (C) 2019 Andreas Füglistaler <andreas.fueglistaler@epfl.ch>
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

for f in input/*.pdb;do
	# copy 
	../bin/copy input/$f.pdb | diff output/"$f"_copy.pdb
done
