#!/usr/bin/env python3

# Copyright (C) 2019 Andreas Füglistaler <andreas.fueglistaler@epfl.ch>
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

import argparse
import os
import sys
import pandas as pd
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

#from pdb_tools import PDB
#from pdb_tools.pdb import PDB

if __name__ == "__main__":
	parser = argparse.ArgumentParser(description='Copy pdb file')
	parser.add_argument("pdb", type=argparse.FileType('r'), nargs='?',
	                    default=sys.stdin, help="pdb-file")

	args  = parser.parse_args()
	#pdb   = PDB(args.pdb)
	#pdb.write()
